---
# tasks file for Status_Check

  - name: Check application status
    uri:
      url: <HealthCheck URL>
      return_content: yes
    register: health
    #failed_when: "'UP' not in health.content"

  - name: Sending an e-mail when application is DOWN
    mail:
     host: smtp.gmail.com
     port: 587
     sender: xxxxxx@gmail.com
     username: xxxxxxxx@gmail.com
     password: xxxxxxx
     to: xxxxxxx@gmail.com
     subject: ALERT:- Application is DOWN
     body:   Ansible Application Status 
   when: "'UP' not in health.content"
   delegate_to: localhost
