---
# tasks file for rabbitmq-server

  - fail: msg="Exiting. this play requires 'action' to be set"
    when: action is undefined

  - name: Check if all packages exist on rabbitmq server
    include_tasks: "{{ action }}.yml" 
