---
# tasks file for postgressql

  - fail: msg="Exiting. this play requires 'action' to be set"
    when: action is undefined

  - name: Check if all packages exist on postgresql server
    include_tasks: "{{ action }}.yml" 
    when: "'verify_install' in action"
