---

- hosts: group1
  tasks:
    - include_role:
        name: apache
      when: "'verify_install' in action"
    - include_role:
        name: common
      when: ("'check_disk' in action") or ("'check_status' in action")
     
- hosts: group2
  tasks:
    - include_role:
        name: postgresql
      when: "'verify_install' in action"
    - include_role:
        name: common
      when: ("'check_disk' in action") or ("'check_status' in action")

- hosts: group3
  tasks:
    - include_role:
        name: rabbitmq
      when: "'verify_install' in action"
    - include_role:
        name: common
      when: ("'check_disk' in action") or ("'check_status' in action")

